version 0.2

phases:
  install:
    commands:
      # download nodeJS and npm
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      # install nodeJS and npm
      - apt-get install -y nodejs
  pre_build:
    commands:
      # install the react/NodeJS dependencies
      - npm install
  build:
    commands:
      # transform reactJS code to static html/js/css
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build